name: A developer's notebook
markdown: redcarpet
redcarpet:
    extensions: ["tables"]
highlighter: pygments
permalink: /blog/:year/:month/:day/:title
url: http://sedden.github.io
author: Stefan Jenkner
gems:
  - jekyll-sitemap
