name: A developer's notebook
markdown: redcarpet
redcarpet:
    extensions: ["tables"]
pygments: true
permalink: /blog/:year/:month/:day/:title
url: http://jenkner.org
author: Stefan Jenkner

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
